### PR TITLE
Infographics

### PR DESCRIPTION
**Pull request by neetuy**
Added infographics
Screenshot_2020-09-14-11-00-02-500_com vachango
Screenshot_2020-09-14-10-53-56-859_com vachango
Screenshot_2020-09-14-10-53-33-628_com vachango
Screenshot_2020-09-14-10-53-29-787_com vachango

### CODE REVIEW

**Comment by samuelanthrayose** [comment]
This is not the Repo that the PR should be pulled to. Please check @neetuy. It should be Bridgeconn's VachanApp Repo.

**Comment by neetuy** [comment]
whenever I click to pull request to Bridgeconn it redirects to
binu-alexander repo but it should be at Bridgeconn. That's why by mistake I
generate pull requests at binu-alenxander.

**Comment by samuelanthrayose** [comment]
> This is not the Repo that the PR should be pulled to. Please check @neetuy. It should be Bridgeconn's VachanApp Repo.

    Ok. Can you delete this PR?

**Comment by neetuy** [comment]
ok,I'll

**Pull request closed without merging**
